include:
  - project: 'docker/process-webhooks'
    file: '/gitlab/deploy.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_TO_BE_DEPLOYED: 'docker/arena-cat'

stages:
  - build
  - deploy

build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache git
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  stage: build
  script:
    # Backend
    - export REPO_NAME=$CI_REGISTRY_IMAGE/arena-cat-backend
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_SLUG
    - export DOCKER_PATH=backend/Dockerfile
    - export DOCKER_CONTEXT=./backend
    - docker build -f $DOCKER_PATH --tag $IMAGE_NAME $DOCKER_CONTEXT
    - docker push $IMAGE_NAME
    # Frontend
    - export REPO_NAME=$CI_REGISTRY_IMAGE/arena-cat-frontend
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_SLUG
    - export DOCKER_PATH=frontend/Dockerfile
    - export DOCKER_CONTEXT=./frontend
    - docker build --build-arg VITE_API_BASE_URL=https://api.softcatala.org/arena_cat/v1/api -f $DOCKER_PATH --tag $IMAGE_NAME $DOCKER_CONTEXT
    - docker push $IMAGE_NAME
    # Inference loader
    - git fetch origin dades_inferencia:refs/remotes/origin/dades_inferencia
    - git checkout origin/dades_inferencia -- data/inferencies
    - export REPO_NAME=$CI_REGISTRY_IMAGE/arena-cat-load-inferences
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_SLUG
    - docker build -f Dockerfile.load-inferences --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  extends:
    .default-deploy
